export CQLSH_NO_BUNDLED=true
cqlsh 127.0.0.1 9042  -e "COPY cja_metadata.calibration (center_name, camera_id, calibration_info) FROM './app/test_config/test-db/calibration.dat';"
cqlsh 127.0.0.1 9042  -e "COPY cja_metadata.language (iso_string, name) FROM './app/test_config/test-db/language.dat';"
cqlsh 127.0.0.1 9042  -e "COPY cja_metadata.working_hours (type) FROM './app/test_config/test-db/working_hours.dat';"
cqlsh 127.0.0.1 9042  -e "COPY cja_metadata.user_status (status) FROM './app/test_config/test-db/user_status.dat';"
cqlsh 127.0.0.1 9042  -e "COPY cja_data.user (email, center_name, designated_zone_name, hashed_pass, is_active, job_title, language, name, photo, role, salt, working_hours) FROM './app/test_config/test-db/user.dat';"
cqlsh 127.0.0.1 9042  -e "COPY cja_data.users_by_location (center_name, email, designated_zone_name, is_active, job_title, language, name, photo, working_hours) FROM './app/test_config/test-db/user_by_location.dat';"
cqlsh 127.0.0.1 9042  -e "COPY cja_data.timeline (center_name, global_identity, epoch_second, age, area, area_type, ethnicity, face_crop, gender, happiness, mask, position_x, position_y) FROM './app/test_config/test-db/timeline.dat';"
cqlsh 127.0.0.1 9042  -e "COPY cja_data.customer_tracker (center_name, global_identity, age_range, live_dwell_time, area, area_type, epoch_second, ethnicity, gender, happiness_index, mask, position_x, position_y) FROM './app/test_config/test-db/customer_tracker.dat';"
cqlsh 127.0.0.1 9042  -e "COPY cja_metadata.areas (center_name, area_type, area_name, polygon) FROM './app/test_config/test-db/areas.dat';"
cqlsh 127.0.0.1 9042  -e "COPY cja_data.center (name, distance_points, floor_plan, floor_plan_px_per_meter, lat, lng, location, manager_email, manager_name, scale_meters) FROM './app/test_config/test-db/centers.dat';"
cqlsh 127.0.0.1 9042  -e "COPY cja_data.dwell_time (center_name, global_identity, area,  epoch_second, dwell_time) FROM './app/test_config/test-db/dwell_time.dat';"
